### ISSUE TITLE
Duplicate snippet problem

### ISSUE THREAD

**Issue by BachiMjavanadze** [rsaz/csharp-snippet-productivity#14]
Your extension comes with C# snippets. I use my own snippets so I do not want duplication of snippets. Of course I can disable all your snippets one by one but it's difficult. Please add setting, something like:

`"csharp-snippet-productivity.EnableSnippets": true/false`

**Comment by rsaz** [comment]
Hi @BachiMjavanadze , this is a tricky one. There is a ticket open for Microsoft to add a feature on vscode in which we could select and disable specific snippets, built-in and user made. As you said, you can enable or disable visibility in each individual one, is a pain, I know. The whole idea of extensions is, to have snippets separated from your extension, so that you could decide to install or not. In my case, when I created the extension I decided to create a bundle with everything necessary for the user to develop in C# within vscode, which also includes the snippets I provided. If the snippets are not good enough, please let me know, I can create/modify to make the snippets even better.

Now, if you really want a final solution, not just for my extension but for other extensions that you are annoyed by, you can use this extension here: https://marketplace.visualstudio.com/items?itemName=svipas.control-snippets
It is an extension that gives you the capability to enable or disable built in or custom made snippets.

![image](https://user-images.githubusercontent.com/4088378/177028969-aadaeedd-9fac-4a84-9f0b-791fb7a23484.png)

**Comment by BachiMjavanadze** [comment]
Thank you for sharing me `Control Snippets`  extension. it is an awesome extension. I did not know about it.
I didn't check your snippets because I always prefer my own, but as you have a goal to do all in one extension, I will check it
