### ISSUE TITLE
Error with folder with spaces

### ISSUE THREAD

**Issue by sarsey-walker** [rsaz/csharp-snippet-productivity#20]
When trying create any project it will not succeed if the there is a space in it. 

![image](https://user-images.githubusercontent.com/54552722/231900834-16b35ecc-92b2-4663-9f37-6143ff0a160f.png)

It should add spaced names in quotes. 

![image](https://user-images.githubusercontent.com/54552722/231901185-2f997907-b575-4dae-9134-ea6ecfd1acca.png)

**Comment by rsaz** [comment]
Hi @sarsey-walker Thanks for reporting this issue.

It was fixed in the latest version of the extension, v2.0.0. The way I opt to fix was, if you type your project name with spaces it will concatenate the name to create the project, for example:

Command: Add Project (From context menu) or Create Project (from Main command)

Case 1:
Project name: My New App
Project is going to be created as: MyNewApp
Case 2: 
Project name: My-New-App
Project is going to be created as: My-New-App
Case 3: 
Project name: My_New_App
Project is going to be created as: My_New_App

Let me know if its all good at your end.

Check it out the news on v2 as well. Happy coding! :)
