### ISSUE TITLE
No Framework to select when creating New Project.

### ISSUE THREAD

**Issue by ayman1988** [rsaz/csharp-snippet-productivity#21]
When Creating new Solution Project...
There is no Framework to select.
![image](https://github.com/rsaz/csharp-snippet-productivity/assets/5460145/b9bb0244-87f0-4c6a-a97a-48cad97edc74)
I have tried to uninstall and install again...

**Comment by ayman1988** [comment]
I fixed it by deleting the extension folder from
.vscode\extensions
now it working...
but I can't see .net 7.0.306
as it installed in my windows

**Comment by ayman1988** [comment]
As Trying to create new project...
The problem reappeared,
There are no frameworks at all...

**Comment by ayman1988** [comment]
Hi...
I found the bug
The bug is in CreateProject.js:
In Write-Output --noEnumeration | dotnet --list-sdks
As the default terminal must be PowerShell
There must be an if to ask for the default Terminal in Vs code.
So, if its cmd...
We must use echo -n.
Mine was cmd...
So, when changing it to PowerShell the problem disappears
There still an issue as it must be closed and opened to refresh the dotnet sdks...

**Comment by rsaz** [comment]
Hi @ayman1988 thank you for your input in the issues.

Both issues you have mentioned above were resolved and it will be released in the next coming version 2.0.

To validate that the sdks were captured on any default prompt we tested with all default windows prompts:

![image](https://github.com/rsaz/csharp-snippet-productivity/assets/4088378/e3797a34-7e3a-4f73-b352-b3f74cbf2792)

Also, the list of SDK's are getting updated as soon as you selected the command Create Project from the menu. You will not need to delete the extension folder in order to get your .net sdk installed. Thanks for your report, please download the latest version. Any new issues, please don't hesitate to contact.

https://marketplace.visualstudio.com/items?itemName=RichardZampieriprog.csharp-snippet-productivity
